package k8sargo

/*

TestNewArgoWorkflowComputeProvider
TestArgoWorkflowComputeProviderSubmitJobs
TestArgoWorkflowComputeProviderSubmitJobsError
TestArgoWorkflowComputeProviderRegisterPlugin
TestArgoWorkflowComputeProviderRegisterPluginError
TestArgoWorkflowComputeProviderUnregisterPlugin
TestArgoWorkflowComputeProviderUnregisterPluginError
TestArgoWorkflowComputeProviderJobLog
TestArgoWorkflowComputeProviderTerminateJobs
TestArgoWorkflowComputeProviderStatus
*/
